server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }
  location /api/products {
    proxy_pass http://product:8081/products;
  }
 
 location /api/inventory {
    proxy_pass http://inventory:8082/inventory;
  }

  location /api/payment {
    proxy_pass http://payment:8083/payment;
  }
}
