networks:
  ecom-net:
    driver: bridge

services:

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - product
      - inventory
      - payment
    restart: unless-stopped
    networks:
      - ecom-net

  product:
    image: ${PRODUCT_IMAGE}
    container_name: product
    expose:
      - "8081"
    restart: unless-stopped
    networks:
      - ecom-net

  inventory:
    image: ${INVENTORY_IMAGE}
    container_name: inventory
    expose:
      - "8082"
    restart: unless-stopped
    networks:
      - ecom-net

  payment:
    image: ${PAYMENT_IMAGE}
    container_name: payment
    expose:
      - "8083"
    restart: unless-stopped
    networks:
      - ecom-net
